INSERT INTO CATEGORY (CATEGORY_TYPE, NAME) VALUES (1, 'Salary');
INSERT INTO CATEGORY (CATEGORY_TYPE, NAME) VALUES (1, 'Bonus');
INSERT INTO CATEGORY (CATEGORY_TYPE, NAME) VALUES (2, 'Food');
INSERT INTO CATEGORY (CATEGORY_TYPE, NAME) VALUES (2, 'Transport');